ports:
    http: 8080
    debug: 5858

auth:
    jwt_secret: 'supersecret'

mongo:
    url: 'mongodb+srv://root:123.com@cluster0-qbqrz.mongodb.net/test?retryWrites=true&w=majority'

# none/debug/info
loglevel: debug

errors:
  'unexpected error': 9001
  'parameter error': 1001